import { PlatformDB } from '../../db/platform';
import { initTenantDB } from '../../db/tenant';

// A mock "AI" agent
export const generateApp = async (prompt: string) => {
  console.log(`Generating app for prompt: ${prompt}`);

  // In a real scenario, this would call an LLM API.
  // Here we hardcode a complex response for "Todo App" which seems to be the canonical demo.

  if (prompt.toLowerCase().includes('todo') || prompt.toLowerCase().includes('task')) {
    return {
      uiSchema: {
        type: 'container',
        props: { className: 'max-w-2xl mx-auto p-4' },
        children: [
          {
            type: 'hero',
            props: {
              title: 'Task Master AI',
              subtitle: 'Generated by AI Agent',
              alignment: 'center'
            }
          },
          {
            type: 'container',
            props: { className: 'flex gap-2 mb-6' },
            children: [
                {
                    type: 'input',
                    props: {
                        name: 'new_task',
                        placeholder: 'Enter a new task...',
                        className: 'flex-1'
                    }
                },
                {
                    type: 'button',
                    props: {
                        label: 'Add Task',
                        variant: 'primary',
                        action: {
                            type: 'server',
                            functionName: 'addTask',
                            collectValues: ['new_task'],
                            onSuccess: 'refresh'
                        }
                    }
                }
            ]
          },
          {
            type: 'list',
            props: {
              itemsSource: {
                  type: 'server',
                  functionName: 'getTasks'
              },
              itemTemplate: {
                  type: 'card',
                  props: {
                      title: '{title}',
                      description: 'Status: {status}',
                      actions: [
                          {
                              label: 'Complete',
                              variant: 'secondary',
                              action: {
                                  type: 'server',
                                  functionName: 'completeTask',
                                  params: { id: '{id}' },
                                  onSuccess: 'refresh'
                              }
                          },
                          {
                            label: 'Delete',
                            variant: 'destructive',
                            action: {
                                type: 'server',
                                functionName: 'deleteTask',
                                params: { id: '{id}' },
                                onSuccess: 'refresh'
                            }
                        }
                      ]
                  }
              }
            }
          }
        ]
      },
      dataSchema: {
        tables: [
          {
            name: 'tasks',
            columns: [
              { name: 'id', type: 'INTEGER PRIMARY KEY AUTOINCREMENT' },
              { name: 'title', type: 'TEXT' },
              { name: 'status', type: 'TEXT DEFAULT "pending"' },
              { name: 'created_at', type: 'DATETIME DEFAULT CURRENT_TIMESTAMP' }
            ]
          }
        ]
      },
      functions: [
        {
          name: 'getTasks',
          code: `
const db = require('./lib/db');

module.exports = async (params) => {
  return db.query("SELECT * FROM tasks ORDER BY created_at DESC");
};
          `
        },
        {
          name: 'addTask',
          code: `
const db = require('./lib/db');

module.exports = async (params) => {
  if (!params.new_task) return { error: 'Task title is required' };
  db.query("INSERT INTO tasks (title) VALUES (?)", params.new_task);
  return { success: true };
};
          `
        },
        {
            name: 'completeTask',
            code: `
const db = require('./lib/db');

module.exports = async (params) => {
  db.query("UPDATE tasks SET status = 'completed' WHERE id = ?", params.id);
  return { success: true };
};
            `
        },
        {
            name: 'deleteTask',
            code: `
const db = require('./lib/db');

module.exports = async (params) => {
  db.query("DELETE FROM tasks WHERE id = ?", params.id);
  return { success: true };
};
            `
        }
      ]
    };
  }

  // Fallback or generic app
  return {
    uiSchema: {
      type: 'hero',
      props: { title: 'Empty App', subtitle: 'Describe your app to generate it!' }
    },
    dataSchema: { tables: [] },
    functions: []
  };
};
